### PR TITLE
Switch deps

### PR DESCRIPTION
**Pull request by Alaneor**
Switched _crypto_ to official implementation.
Also switched _bcrypt-nodejs_ to the generally more used and better maintained _bcrypt_ package. Also got rid of `bcrypt.compareSync()` call to keep it all async so as to not block the whole process.

### CODE REVIEW

**Comment by Alaneor** [comment]
... and, I took the liberty of switching the Travis builds to use dockerised environment instead of the full VM environment. This should not cause any side-effects in the long term unless there is need to use `sudo` for some reason during the builds.

**Comment by jaumard** [comment]
Thanks for this ! I just learn we can throw errors on then method of promises ^^ instead of returning rejected promise. Make code much easy :)

**Comment by Alaneor** [comment]
Exactly. :) But careful with that, you can only throw them from the main function. You must use `reject()` if you need to mix promises with callbacks.

**Comment by jaumard** [comment]
I'll keep this in mind ! Thanks ! :D

**Pull request merged**
