### PR TITLE
Fix Passport model for Mongoose and authentication for third-party

### PR DESCRIPTION
**Pull request by ianvieira**
As I told in my issue, the Mongoose model validation is not the expected, this commit changes it to the expected validation. 
Another issue is that the authentication with third-party was not working in several scenarios, this commit fixes the authentication problems. The callback was trying to use the findOne option in the find, Mongoose and Waterline don't allow that option on FootprintService with a criteria, just with the model ID. Also, manually add the User ID on the Passport model, as trails don't do it (at least with mongoose), failing the whole authentication.

The findAssociation has an issue on trailpack-mongoose, where the Parent Model name is hardcoded as 'User', I already filed a PR for that change, so until we have this change, the Mongoose authentication can fail.

### CODE REVIEW

**Comment by jaumard** [comment]
Ok that's a big one ^^ for the model it's ok, for the other things I'll take a look more deeply later next week as I'm not here this weekend.
But is there no existing tests for the part you change ? Is it possible to add some ? Because tests are running with the 3 ORM so it will be more easier to see if something is breaking or not working correctly, even more for the future

**Comment by jaumard** [comment]
in the mean time @LobeTia can you also take a look at this PR please ? As you do the mongoose part it make sens :) 
Thanks guys

**Comment by ianvieira** [comment]
Yeah, of course I can write a test in the future, in fact for Mongoose at least the third-party login was not working at all, so I believe a test for the feature is better than to my changes. As I said, I don't know if it affected the others ORMs too...

**Comment by jaumard** [comment]
I'll will retrieve your version and make some tests with local and third party connexion/registration and see if it's all good. I'll try to do it this week thanks

**Comment by jaumard** [comment]
I test local register/login and GitHub/Twitter third party login with Sequelize/Waterline/Mongoose and all good ! :) 
Thanks for this

**Pull request merged**
