### PR TITLE
Allow users without a Passport, and Sequelize fix

### PR DESCRIPTION
**Pull request by skinny**
Fix association in Sequelize

### CODE REVIEW

**Comment by jaumard** [comment]
Do you want me to merge this now ? Or I can wait a little to have also the `FootprintService` to retrieve informations. 
Let me know if you make it to work :D

**Comment by skinny** [comment]
Yeah, keep it open for a little bit. I'm still working on this. thanks

**Comment by jaumard** [comment]
Look great so far :D all `app.orm` call have to be replace be the `FootprintService` calls. Currently tests test only register/login from local strategy. All oauth, oauth2 ect... need to be test manually because they don't use same code. 
If you have some ideas to create some tests for oauth, oauth2 stragtegies let me know ! I'm interesting to make them, it will be more simple to avoid problems in the future :) 
Thanks for your work!

**Comment by jaumard** [comment]
@skinny I just push modifications on tests. Now `npm test` test first waterline and then sequelize (but only for register/login (not for oauth and co...) like this it can help you with this :) tests are failing for now on my branch.

**Comment by jaumard** [comment]
@skinny what is your status about this ? did you need some help ? :)

**Comment by skinny** [comment]
Not yet ;-) I have that thing called family which requires some attention during the weekend. To be continued ;-)

**Comment by jaumard** [comment]
Ha ha no problem ! Just wanted to know :D enjoy with your family !

**Comment by jaumard** [comment]
Any update on this @skinny ? Can you at least synchronize the branch. I'll merge this like this I can continue this.
Thanks :)

**Comment by jaumard** [comment]
Liittle up :) @skinny

**Pull request closed without merging**
