### PR TITLE
Refactoring Promises, push code more to left

### PR DESCRIPTION
**Pull request by Alaneor**
Tried hard to push the code more to the left by removing `else` and `else if` blocks where possible. Also tweaked how `.catch()` blocks are handled.

Fixed one bug: In the `PassportService.disconnect()` function, I fixed a potential issue where a request to disconnect a non-existent passport would silently pass. Perhaps this was the intended behaviour so please review carefully here. I changed it to throw `E_USER_NO_PASSWORD`.

Changed: In _archetype/config/session.js_, I changed `process.env.tokenSecret` to `process.env.TOKEN_SECRET` as that's usually the format of env vars most commonly used.

There are a couple of coding style tweaks, but if you don't like those let me know and I'll just revert them back, no hard feelings. :)

### CODE REVIEW

**Comment by jaumard** [comment]
For `PassportService.disconnect` I suppose both are good behaviors cause some will prefer an error an other will prefer a silent failure ^^ so no problem to keep the error and if users want to ignore it they can.

In fact I don't like when there multiple `return` in a function, I found it more complicate to understand the all things cause you have multiple break point. For me a function should have a start and a end not multiple end. But that's my opinion only ^^ 

I understand for the `catch`, I'm quite new to Node so I have some things to learn ^^ thanks for your feedback ! Also I retrieve a lot of code from another repo sails-hook-passport I wrote some time ago (not in es2015) and didn't refactor all of it :)

**Comment by Alaneor** [comment]
I can understand the concern with multiple `return` statements. I have to admit, I got into the habit of abusing `return` as a short-circuiting mechanism. The whole point of that is to get the hell out of the function as soon as possible. While working with Node, I frequently found myself doing nested async calls and whatnot and the code just kept shifting to the right. This was a part of dealing with that shift.

Since most of the changes in this PR are about style, perhaps it would be best to just close this and apply the two other changes separately?

**Comment by jaumard** [comment]
I think it should be more easy to make changes separately yes. Can you make another PR or do you want me to push the changes ? I don't mind do it :) as you want

**Comment by Alaneor** [comment]
You will probably get it done much faster. :) If you don't mind, I would appreciate that! Thanks!

**Comment by jaumard** [comment]
No problem it's done ;) thanks to you for helping me with that !

**Pull request closed without merging**
