### PR TITLE
Add js-data

### PR DESCRIPTION
**Pull request by scott-wyatt**
This is sans test for JS-data, as I am still finalizing the ORM, but this will be the schema it supports.

### CODE REVIEW

**Comment by jaumard** [comment]
Thanks for this ! Looks great ! I'll wait your tests before merging this :) or do you prefer to make another PR later ?

**Comment by scott-wyatt** [comment]
I'll put the tests back in first and then let you know! Cheers!

**Comment by jaumard** [comment]
Hey @scott-wyatt ! What's the status about this ? :) now tests can support any ORM easily ;) and this module support 2 ORM already (soon 3 with mongoose) and maybe 4 with this one then ^^

**Comment by scott-wyatt** [comment]
We should close this, I won't be supporting js-data anytime soon and I don't want people to get confused. :-(

**Pull request closed without merging**
